#!/sbin/runscript

depend() {
    use dns net logger
}

start() {
    ebegin "Starting Automatic Hardware Setup daemon"
    start-stop-daemon --start --quiet \
        --exec /usr/sbin/ahws --pidfile /var/run/ahws.pid
    eend $?
}

stop() {
    ebegin "Stopping Automatic Hardware Setup daemon"
    start-stop-daemon --stop --quiet \
        --exec /usr/sbin/ahws --pidfile /var/run/ahws.pid
    eend $?
}
