# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qdesktop.ui'
#
# Created: Sun May 18 13:36:03 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(445, 326)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.DesktopView = QtGui.QListView(self.centralwidget)
        self.DesktopView.setGeometry(QtCore.QRect(10, 10, 419, 279))
        self.DesktopView.setFrameShape(QtGui.QFrame.NoFrame)
        self.DesktopView.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.DesktopView.setObjectName(_fromUtf8("DesktopView"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 445, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuActions = QtGui.QMenu(self.menubar)
        self.menuActions.setObjectName(_fromUtf8("menuActions"))
        self.menuNew = QtGui.QMenu(self.menuActions)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/usr/share/pfm/resources/add.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuNew.setIcon(icon)
        self.menuNew.setObjectName(_fromUtf8("menuNew"))
        self.menuArchvie = QtGui.QMenu(self.menuActions)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/usr/share/pfm/resources/application-x-compress.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuArchvie.setIcon(icon1)
        self.menuArchvie.setObjectName(_fromUtf8("menuArchvie"))
        MainWindow.setMenuBar(self.menubar)
        self.actionDummy = QtGui.QAction(MainWindow)
        self.actionDummy.setObjectName(_fromUtf8("actionDummy"))
        self.actionOpen = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/usr/share/pfm/resources/fileopen.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon2)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionCut = QtGui.QAction(MainWindow)
        self.actionCut.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/usr/share/pfm/resources/editcut.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon3)
        self.actionCut.setObjectName(_fromUtf8("actionCut"))
        self.actionCopy = QtGui.QAction(MainWindow)
        self.actionCopy.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/usr/share/pfm/resources/edit-copy.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon4)
        self.actionCopy.setObjectName(_fromUtf8("actionCopy"))
        self.actionPaste = QtGui.QAction(MainWindow)
        self.actionPaste.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/usr/share/pfm/resources/gtk-paste.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon5)
        self.actionPaste.setObjectName(_fromUtf8("actionPaste"))
        self.actionRename = QtGui.QAction(MainWindow)
        self.actionRename.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/usr/share/pfm/resources/edit-rename.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRename.setIcon(icon6)
        self.actionRename.setObjectName(_fromUtf8("actionRename"))
        self.actionDelete = QtGui.QAction(MainWindow)
        self.actionDelete.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/usr/share/pfm/resources/editdelete.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon7)
        self.actionDelete.setObjectName(_fromUtf8("actionDelete"))
        self.actionProperties = QtGui.QAction(MainWindow)
        self.actionProperties.setEnabled(False)
        self.actionProperties.setObjectName(_fromUtf8("actionProperties"))
        self.actionFile = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/usr/share/pfm/resources/filenew.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFile.setIcon(icon8)
        self.actionFile.setObjectName(_fromUtf8("actionFile"))
        self.actionFolder = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/usr/share/pfm/resources/folder_new.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFolder.setIcon(icon9)
        self.actionFolder.setObjectName(_fromUtf8("actionFolder"))
        self.actionDecompress = QtGui.QAction(MainWindow)
        self.actionDecompress.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/usr/share/pfm/resources/cab_extract.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDecompress.setIcon(icon10)
        self.actionDecompress.setObjectName(_fromUtf8("actionDecompress"))
        self.actionCompress_gzip = QtGui.QAction(MainWindow)
        self.actionCompress_gzip.setEnabled(False)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/usr/share/pfm/resources/application-x-gzip.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCompress_gzip.setIcon(icon11)
        self.actionCompress_gzip.setObjectName(_fromUtf8("actionCompress_gzip"))
        self.actionCompress_bzip2 = QtGui.QAction(MainWindow)
        self.actionCompress_bzip2.setEnabled(False)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/usr/share/pfm/resources/application-x-bzip.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCompress_bzip2.setIcon(icon12)
        self.actionCompress_bzip2.setObjectName(_fromUtf8("actionCompress_bzip2"))
        self.actionCompress_xz = QtGui.QAction(MainWindow)
        self.actionCompress_xz.setEnabled(False)
        self.actionCompress_xz.setIcon(icon1)
        self.actionCompress_xz.setObjectName(_fromUtf8("actionCompress_xz"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/usr/share/pfm/resources/redhat-tools.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPreferences.setIcon(icon13)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.menuNew.addAction(self.actionFile)
        self.menuNew.addAction(self.actionFolder)
        self.menuArchvie.addAction(self.actionDecompress)
        self.menuArchvie.addAction(self.actionCompress_gzip)
        self.menuArchvie.addAction(self.actionCompress_bzip2)
        self.menuArchvie.addAction(self.actionCompress_xz)
        self.menuActions.addAction(self.actionOpen)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionCut)
        self.menuActions.addAction(self.actionCopy)
        self.menuActions.addAction(self.actionPaste)
        self.menuActions.addAction(self.actionRename)
        self.menuActions.addAction(self.actionDelete)
        self.menuActions.addAction(self.actionProperties)
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.menuNew.menuAction())
        self.menuActions.addAction(self.menuArchvie.menuAction())
        self.menuActions.addSeparator()
        self.menuActions.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuActions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "QDesktop", None))
        self.menuActions.setTitle(_translate("MainWindow", "Actions", None))
        self.menuNew.setTitle(_translate("MainWindow", "New", None))
        self.menuArchvie.setTitle(_translate("MainWindow", "Archvie", None))
        self.actionDummy.setText(_translate("MainWindow", "dummy", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionCut.setText(_translate("MainWindow", "Cut", None))
        self.actionCopy.setText(_translate("MainWindow", "Copy", None))
        self.actionPaste.setText(_translate("MainWindow", "Paste", None))
        self.actionRename.setText(_translate("MainWindow", "Rename", None))
        self.actionDelete.setText(_translate("MainWindow", "Delete", None))
        self.actionProperties.setText(_translate("MainWindow", "Properties", None))
        self.actionFile.setText(_translate("MainWindow", "File", None))
        self.actionFolder.setText(_translate("MainWindow", "Folder", None))
        self.actionDecompress.setText(_translate("MainWindow", "Decompress", None))
        self.actionCompress_gzip.setText(_translate("MainWindow", "Compress (gzip)", None))
        self.actionCompress_bzip2.setText(_translate("MainWindow", "Compress (bzip2)", None))
        self.actionCompress_xz.setText(_translate("MainWindow", "Compress (xz)", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))

import qdesktop_rc
