# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_libudev', [dirname(__file__)])
        except ImportError:
            import _libudev
            return _libudev
        if fp is not None:
            try:
                _mod = imp.load_module('_libudev', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _libudev = swig_import_helper()
    del swig_import_helper
else:
    import _libudev
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def udev_ref(*args):
  return _libudev.udev_ref(*args)
udev_ref = _libudev.udev_ref

def udev_unref(*args):
  return _libudev.udev_unref(*args)
udev_unref = _libudev.udev_unref

def udev_new():
  return _libudev.udev_new()
udev_new = _libudev.udev_new

def udev_set_log_fn(*args):
  return _libudev.udev_set_log_fn(*args)
udev_set_log_fn = _libudev.udev_set_log_fn

def udev_get_log_priority(*args):
  return _libudev.udev_get_log_priority(*args)
udev_get_log_priority = _libudev.udev_get_log_priority

def udev_set_log_priority(*args):
  return _libudev.udev_set_log_priority(*args)
udev_set_log_priority = _libudev.udev_set_log_priority

def udev_get_userdata(*args):
  return _libudev.udev_get_userdata(*args)
udev_get_userdata = _libudev.udev_get_userdata

def udev_set_userdata(*args):
  return _libudev.udev_set_userdata(*args)
udev_set_userdata = _libudev.udev_set_userdata

def udev_list_entry_get_next(*args):
  return _libudev.udev_list_entry_get_next(*args)
udev_list_entry_get_next = _libudev.udev_list_entry_get_next

def udev_list_entry_get_by_name(*args):
  return _libudev.udev_list_entry_get_by_name(*args)
udev_list_entry_get_by_name = _libudev.udev_list_entry_get_by_name

def udev_list_entry_get_name(*args):
  return _libudev.udev_list_entry_get_name(*args)
udev_list_entry_get_name = _libudev.udev_list_entry_get_name

def udev_list_entry_get_value(*args):
  return _libudev.udev_list_entry_get_value(*args)
udev_list_entry_get_value = _libudev.udev_list_entry_get_value

def udev_device_ref(*args):
  return _libudev.udev_device_ref(*args)
udev_device_ref = _libudev.udev_device_ref

def udev_device_unref(*args):
  return _libudev.udev_device_unref(*args)
udev_device_unref = _libudev.udev_device_unref

def udev_device_get_udev(*args):
  return _libudev.udev_device_get_udev(*args)
udev_device_get_udev = _libudev.udev_device_get_udev

def udev_device_new_from_syspath(*args):
  return _libudev.udev_device_new_from_syspath(*args)
udev_device_new_from_syspath = _libudev.udev_device_new_from_syspath

def udev_device_new_from_devnum(*args):
  return _libudev.udev_device_new_from_devnum(*args)
udev_device_new_from_devnum = _libudev.udev_device_new_from_devnum

def udev_device_new_from_subsystem_sysname(*args):
  return _libudev.udev_device_new_from_subsystem_sysname(*args)
udev_device_new_from_subsystem_sysname = _libudev.udev_device_new_from_subsystem_sysname

def udev_device_new_from_device_id(*args):
  return _libudev.udev_device_new_from_device_id(*args)
udev_device_new_from_device_id = _libudev.udev_device_new_from_device_id

def udev_device_new_from_environment(*args):
  return _libudev.udev_device_new_from_environment(*args)
udev_device_new_from_environment = _libudev.udev_device_new_from_environment

def udev_device_get_parent(*args):
  return _libudev.udev_device_get_parent(*args)
udev_device_get_parent = _libudev.udev_device_get_parent

def udev_device_get_parent_with_subsystem_devtype(*args):
  return _libudev.udev_device_get_parent_with_subsystem_devtype(*args)
udev_device_get_parent_with_subsystem_devtype = _libudev.udev_device_get_parent_with_subsystem_devtype

def udev_device_get_devpath(*args):
  return _libudev.udev_device_get_devpath(*args)
udev_device_get_devpath = _libudev.udev_device_get_devpath

def udev_device_get_subsystem(*args):
  return _libudev.udev_device_get_subsystem(*args)
udev_device_get_subsystem = _libudev.udev_device_get_subsystem

def udev_device_get_devtype(*args):
  return _libudev.udev_device_get_devtype(*args)
udev_device_get_devtype = _libudev.udev_device_get_devtype

def udev_device_get_syspath(*args):
  return _libudev.udev_device_get_syspath(*args)
udev_device_get_syspath = _libudev.udev_device_get_syspath

def udev_device_get_sysname(*args):
  return _libudev.udev_device_get_sysname(*args)
udev_device_get_sysname = _libudev.udev_device_get_sysname

def udev_device_get_sysnum(*args):
  return _libudev.udev_device_get_sysnum(*args)
udev_device_get_sysnum = _libudev.udev_device_get_sysnum

def udev_device_get_devnode(*args):
  return _libudev.udev_device_get_devnode(*args)
udev_device_get_devnode = _libudev.udev_device_get_devnode

def udev_device_get_is_initialized(*args):
  return _libudev.udev_device_get_is_initialized(*args)
udev_device_get_is_initialized = _libudev.udev_device_get_is_initialized

def udev_device_get_devlinks_list_entry(*args):
  return _libudev.udev_device_get_devlinks_list_entry(*args)
udev_device_get_devlinks_list_entry = _libudev.udev_device_get_devlinks_list_entry

def udev_device_get_properties_list_entry(*args):
  return _libudev.udev_device_get_properties_list_entry(*args)
udev_device_get_properties_list_entry = _libudev.udev_device_get_properties_list_entry

def udev_device_get_tags_list_entry(*args):
  return _libudev.udev_device_get_tags_list_entry(*args)
udev_device_get_tags_list_entry = _libudev.udev_device_get_tags_list_entry

def udev_device_get_sysattr_list_entry(*args):
  return _libudev.udev_device_get_sysattr_list_entry(*args)
udev_device_get_sysattr_list_entry = _libudev.udev_device_get_sysattr_list_entry

def udev_device_get_property_value(*args):
  return _libudev.udev_device_get_property_value(*args)
udev_device_get_property_value = _libudev.udev_device_get_property_value

def udev_device_get_driver(*args):
  return _libudev.udev_device_get_driver(*args)
udev_device_get_driver = _libudev.udev_device_get_driver

def udev_device_get_devnum(*args):
  return _libudev.udev_device_get_devnum(*args)
udev_device_get_devnum = _libudev.udev_device_get_devnum

def udev_device_get_action(*args):
  return _libudev.udev_device_get_action(*args)
udev_device_get_action = _libudev.udev_device_get_action

def udev_device_get_seqnum(*args):
  return _libudev.udev_device_get_seqnum(*args)
udev_device_get_seqnum = _libudev.udev_device_get_seqnum

def udev_device_get_usec_since_initialized(*args):
  return _libudev.udev_device_get_usec_since_initialized(*args)
udev_device_get_usec_since_initialized = _libudev.udev_device_get_usec_since_initialized

def udev_device_get_sysattr_value(*args):
  return _libudev.udev_device_get_sysattr_value(*args)
udev_device_get_sysattr_value = _libudev.udev_device_get_sysattr_value

def udev_device_set_sysattr_value(*args):
  return _libudev.udev_device_set_sysattr_value(*args)
udev_device_set_sysattr_value = _libudev.udev_device_set_sysattr_value

def udev_device_has_tag(*args):
  return _libudev.udev_device_has_tag(*args)
udev_device_has_tag = _libudev.udev_device_has_tag

def udev_monitor_ref(*args):
  return _libudev.udev_monitor_ref(*args)
udev_monitor_ref = _libudev.udev_monitor_ref

def udev_monitor_unref(*args):
  return _libudev.udev_monitor_unref(*args)
udev_monitor_unref = _libudev.udev_monitor_unref

def udev_monitor_get_udev(*args):
  return _libudev.udev_monitor_get_udev(*args)
udev_monitor_get_udev = _libudev.udev_monitor_get_udev

def udev_monitor_new_from_netlink(*args):
  return _libudev.udev_monitor_new_from_netlink(*args)
udev_monitor_new_from_netlink = _libudev.udev_monitor_new_from_netlink

def udev_monitor_enable_receiving(*args):
  return _libudev.udev_monitor_enable_receiving(*args)
udev_monitor_enable_receiving = _libudev.udev_monitor_enable_receiving

def udev_monitor_set_receive_buffer_size(*args):
  return _libudev.udev_monitor_set_receive_buffer_size(*args)
udev_monitor_set_receive_buffer_size = _libudev.udev_monitor_set_receive_buffer_size

def udev_monitor_get_fd(*args):
  return _libudev.udev_monitor_get_fd(*args)
udev_monitor_get_fd = _libudev.udev_monitor_get_fd

def udev_monitor_receive_device(*args):
  return _libudev.udev_monitor_receive_device(*args)
udev_monitor_receive_device = _libudev.udev_monitor_receive_device

def udev_monitor_filter_add_match_subsystem_devtype(*args):
  return _libudev.udev_monitor_filter_add_match_subsystem_devtype(*args)
udev_monitor_filter_add_match_subsystem_devtype = _libudev.udev_monitor_filter_add_match_subsystem_devtype

def udev_monitor_filter_add_match_tag(*args):
  return _libudev.udev_monitor_filter_add_match_tag(*args)
udev_monitor_filter_add_match_tag = _libudev.udev_monitor_filter_add_match_tag

def udev_monitor_filter_update(*args):
  return _libudev.udev_monitor_filter_update(*args)
udev_monitor_filter_update = _libudev.udev_monitor_filter_update

def udev_monitor_filter_remove(*args):
  return _libudev.udev_monitor_filter_remove(*args)
udev_monitor_filter_remove = _libudev.udev_monitor_filter_remove

def udev_enumerate_ref(*args):
  return _libudev.udev_enumerate_ref(*args)
udev_enumerate_ref = _libudev.udev_enumerate_ref

def udev_enumerate_unref(*args):
  return _libudev.udev_enumerate_unref(*args)
udev_enumerate_unref = _libudev.udev_enumerate_unref

def udev_enumerate_get_udev(*args):
  return _libudev.udev_enumerate_get_udev(*args)
udev_enumerate_get_udev = _libudev.udev_enumerate_get_udev

def udev_enumerate_new(*args):
  return _libudev.udev_enumerate_new(*args)
udev_enumerate_new = _libudev.udev_enumerate_new

def udev_enumerate_add_match_subsystem(*args):
  return _libudev.udev_enumerate_add_match_subsystem(*args)
udev_enumerate_add_match_subsystem = _libudev.udev_enumerate_add_match_subsystem

def udev_enumerate_add_nomatch_subsystem(*args):
  return _libudev.udev_enumerate_add_nomatch_subsystem(*args)
udev_enumerate_add_nomatch_subsystem = _libudev.udev_enumerate_add_nomatch_subsystem

def udev_enumerate_add_match_sysattr(*args):
  return _libudev.udev_enumerate_add_match_sysattr(*args)
udev_enumerate_add_match_sysattr = _libudev.udev_enumerate_add_match_sysattr

def udev_enumerate_add_nomatch_sysattr(*args):
  return _libudev.udev_enumerate_add_nomatch_sysattr(*args)
udev_enumerate_add_nomatch_sysattr = _libudev.udev_enumerate_add_nomatch_sysattr

def udev_enumerate_add_match_property(*args):
  return _libudev.udev_enumerate_add_match_property(*args)
udev_enumerate_add_match_property = _libudev.udev_enumerate_add_match_property

def udev_enumerate_add_match_sysname(*args):
  return _libudev.udev_enumerate_add_match_sysname(*args)
udev_enumerate_add_match_sysname = _libudev.udev_enumerate_add_match_sysname

def udev_enumerate_add_match_tag(*args):
  return _libudev.udev_enumerate_add_match_tag(*args)
udev_enumerate_add_match_tag = _libudev.udev_enumerate_add_match_tag

def udev_enumerate_add_match_parent(*args):
  return _libudev.udev_enumerate_add_match_parent(*args)
udev_enumerate_add_match_parent = _libudev.udev_enumerate_add_match_parent

def udev_enumerate_add_match_is_initialized(*args):
  return _libudev.udev_enumerate_add_match_is_initialized(*args)
udev_enumerate_add_match_is_initialized = _libudev.udev_enumerate_add_match_is_initialized

def udev_enumerate_add_syspath(*args):
  return _libudev.udev_enumerate_add_syspath(*args)
udev_enumerate_add_syspath = _libudev.udev_enumerate_add_syspath

def udev_enumerate_scan_devices(*args):
  return _libudev.udev_enumerate_scan_devices(*args)
udev_enumerate_scan_devices = _libudev.udev_enumerate_scan_devices

def udev_enumerate_scan_subsystems(*args):
  return _libudev.udev_enumerate_scan_subsystems(*args)
udev_enumerate_scan_subsystems = _libudev.udev_enumerate_scan_subsystems

def udev_enumerate_get_list_entry(*args):
  return _libudev.udev_enumerate_get_list_entry(*args)
udev_enumerate_get_list_entry = _libudev.udev_enumerate_get_list_entry

def udev_queue_ref(*args):
  return _libudev.udev_queue_ref(*args)
udev_queue_ref = _libudev.udev_queue_ref

def udev_queue_unref(*args):
  return _libudev.udev_queue_unref(*args)
udev_queue_unref = _libudev.udev_queue_unref

def udev_queue_get_udev(*args):
  return _libudev.udev_queue_get_udev(*args)
udev_queue_get_udev = _libudev.udev_queue_get_udev

def udev_queue_new(*args):
  return _libudev.udev_queue_new(*args)
udev_queue_new = _libudev.udev_queue_new

def udev_queue_get_kernel_seqnum(*args):
  return _libudev.udev_queue_get_kernel_seqnum(*args)
udev_queue_get_kernel_seqnum = _libudev.udev_queue_get_kernel_seqnum

def udev_queue_get_udev_seqnum(*args):
  return _libudev.udev_queue_get_udev_seqnum(*args)
udev_queue_get_udev_seqnum = _libudev.udev_queue_get_udev_seqnum

def udev_queue_get_udev_is_active(*args):
  return _libudev.udev_queue_get_udev_is_active(*args)
udev_queue_get_udev_is_active = _libudev.udev_queue_get_udev_is_active

def udev_queue_get_queue_is_empty(*args):
  return _libudev.udev_queue_get_queue_is_empty(*args)
udev_queue_get_queue_is_empty = _libudev.udev_queue_get_queue_is_empty

def udev_queue_get_seqnum_is_finished(*args):
  return _libudev.udev_queue_get_seqnum_is_finished(*args)
udev_queue_get_seqnum_is_finished = _libudev.udev_queue_get_seqnum_is_finished

def udev_queue_get_seqnum_sequence_is_finished(*args):
  return _libudev.udev_queue_get_seqnum_sequence_is_finished(*args)
udev_queue_get_seqnum_sequence_is_finished = _libudev.udev_queue_get_seqnum_sequence_is_finished

def udev_queue_get_queued_list_entry(*args):
  return _libudev.udev_queue_get_queued_list_entry(*args)
udev_queue_get_queued_list_entry = _libudev.udev_queue_get_queued_list_entry

def udev_hwdb_new(*args):
  return _libudev.udev_hwdb_new(*args)
udev_hwdb_new = _libudev.udev_hwdb_new

def udev_hwdb_ref(*args):
  return _libudev.udev_hwdb_ref(*args)
udev_hwdb_ref = _libudev.udev_hwdb_ref

def udev_hwdb_unref(*args):
  return _libudev.udev_hwdb_unref(*args)
udev_hwdb_unref = _libudev.udev_hwdb_unref

def udev_hwdb_get_properties_list_entry(*args):
  return _libudev.udev_hwdb_get_properties_list_entry(*args)
udev_hwdb_get_properties_list_entry = _libudev.udev_hwdb_get_properties_list_entry

def udev_util_encode_string(*args):
  return _libudev.udev_util_encode_string(*args)
udev_util_encode_string = _libudev.udev_util_encode_string
# This file is compatible with both classic and new-style classes.


