#!/sbin/runscript

depend() {
    use dns net logger dbus
}

start() {
    ebegin "Starting Source Package Manager daemon"
    start-stop-daemon --start --quiet \
        --background --exec /usr/sbin/spmd --pidfile /var/run/spmd.pid
    eend $?
}

stop() {
    ebegin "Stopping Source Package Manager daemon"
    start-stop-daemon --stop --quiet \
        --exec /usr/sbin/spmd --pidfile /var/run/spmd.pid
    eend $?
}
