#!/bin/sh

set -e

# Hardware: PLAYSTATION(R)3 Controller
# Reason: requires manual intervention to make it work

. /etc/ahws.d/common

case "$1" in
    add) modprobe -qba uinput; install_package xboxdrv
         service_enable xboxdrv && service_start xboxdrv ;;
    online) modprobe -qba uinput; install_package xboxdrv
            service_enable xboxdrv && service_start xboxdrv ;;
    changed) true ;; # ignored
    offline) service_stop xboxdrv && service_disable xboxdrv ;;
    remove) service_stop xboxdrv && service_disable xboxdrv ;;
    *) echo "Unknown event: $1" && exit 1 ;;
esac