#!/bin/sh

set -e

# Hardware: NVIDIA Corporation MCP79 [GeForce 8200M G] (rev b1)
# Reason: suspend does not work, system locks up if KMS is on with nouveau

. /etc/ahws.d/common

case "$1" in
    add) install_nvidia || { kms_disable && xvesa_enable } ;;
    online) install_nvidia || { kms_disable && xvesa_enable } ;;
    changed) true ;; # ignored
    offline) remove_nvidia && kms_enable && xvesa_disable ;;
    remove) remove_nvidia && kms_enable && xvesa_disable ;;
    *) echo "Unknown event: $1" && exit 1 ;;
esac